// OpsRelay Production Configuration
// Auto-generated by deployment script — do not edit manually
// API Gateway: https://4q0wc7pbk4.execute-api.ap-south-1.amazonaws.com/prod
window.OPSR_CONFIG = {
  apiBaseUrl: 'https://4q0wc7pbk4.execute-api.ap-south-1.amazonaws.com/prod/api',
  region: 'ap-south-1',
  environment: 'production',
  cognito: {
    userPoolId: 'ap-south-1_8RwKqg1pG',
    clientId: '3b5g8ubijpcdg032lhmdouc9is',
    endpoint: 'https://cognito-idp.ap-south-1.amazonaws.com'
  }
};
